spring:
  application:
    name: ms.manga.store
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
jwt:
  access:
    token:
      secret: ${JWT_ACCESS_TOKEN_SECRET}
      validity:
        seconds: ${JWT_ACCESS_TOKEN_VALIDITY_SECONDS}